### ISSUE TITLE
Work with python-scss

### ISSUE THREAD

**Issue by QuLogic** [dahlia/libsass-python#1]
This isn't really a bug. I just wanted to point out the other python wrapper here: https://github.com/pistolero/python-scss I haven't really looked too deeply into whether one is better than the other. However, I do see that python-scss uses libsass as a git subrepo, which might be a better idea if you don't intend the Python stuff to be merged with libsass. Anyway, I think it would be better to pool resources, don't confuse users by having two wrappers, etc.

See also: https://github.com/pistolero/python-scss/issues/7

**Comment by dahlia** [comment]
Python-scss doesn’t seem in that active development, and I have no plan to merge libsass-python with python-scss anymore — and they also seem to think so.

**Comment by QuLogic** [comment]
Seems to make sense at this point.
