### ISSUE TITLE
Adding Python 3.5 build on AppVeyor CI

### ISSUE THREAD

**Issue by dahlia** [dahlia/libsass-python#101]
It currently builds on only Python 2.7, 3.3, and 3.4.

**Comment by asottile** [comment]
Should we drop 3.3 at the same time?  I doubt many people are using 3.3 when 3.4 / 3.5 are readily available

**Comment by dahlia** [comment]
If it needs more cost, we’d better to drop Python 3.3. Do we put additional
efforts to make it compatible with 3.3?

**Comment by asottile** [comment]
I don't think we currently put in any special casing to support py33 -- dropping would just be to speed up the total build time

**Comment by dahlia** [comment]
So, we can skip Python 3.3 build on AppVeyor, but maintain 3.3 on Travis CI
at the same time.
