### ISSUE TITLE
Another watcher in another package ?

### ISSUE THREAD

**Issue by sveetch** [dahlia/libsass-python#115]
Currently the watch mode exist for sassc, but compared to the Compass one, it lacks of watching for imported files in the scss source given as first argument (SCSS_FILE).

So i was thinking about developing a watcher that would be able to do that using https://github.com/gorakhargosh/watchdog and some sass parsing stuff. 

And i'm wondering if you prefer that i do it in another package like "libsass-python-watcher" or start to include it in your wrapper, because i'm pretty sure you wont want dependancies like watchdog in your wrapper, no ?

**Comment by asottile** [comment]
I'm in favor of factoring out the watch mode.

At work we instead use a more generic watcher: https://github.com/kimmobrunfeldt/chokidar-cli

@dahlia what do you think about deprecating (and eventually factoring out) the watch mode?

**Comment by sveetch** [comment]
I allready started the project on https://github.com/sveetch/boussole but didn't post about it here since i'm currently working on the watcher.

**Comment by samuelcolvin** [comment]
I've used both watchdog and https://github.com/seb-m/pyinotify although the latter has quite poor and hard to find documentation (look in the wiki) it's far simpler and has ended up with better solutions for me.

**Comment by sveetch** [comment]
@asottile @dahlia sorry to disturbed you with this issue, i won't dare to close this issue myself, but as i'm very happy with my Boussole solution, be free to close it if you want.

**Comment by asottile** [comment]
`--watch` has been deprecated and will be removed in a future version #156
