### ISSUE TITLE
Compile with dirname fails silently when paths are wrong

### ISSUE THREAD

**Issue by LynnCo** [dahlia/libsass-python#116]
Should fail with an OSError

**Comment by asottile** [comment]
Please provide the following so we can appropriately handle your issue:
- What version you're using
- A small reproducible example
- What the expected behaviour in that case should be

**Comment by asottile** [comment]
I think (?) I figured out what you meant so I'm fixing it: #119

**Comment by LynnCo** [comment]
Yep, its exactly that

**Comment by asottile** [comment]
This is part of 0.11.0!
