### ISSUE TITLE
Compile error: undefined variable

### ISSUE THREAD

**Issue by erbridge** [dahlia/libsass-python#122]
After upgrading to `0.10.1` from `0.10.0`, I get the following error:

```
sass.CompileError: b'Error: Undefined variable: "$target".\n        on line 8 of indigo/static/styles/mixins/_units.scss\n>>     @return calc-rem($target, $context);\n   ---------------------^\n'
```

`_units.scss` is:

```scss
@import 'styles/variables/defaults';

@function calc-rem($target, $context: $root-font-size) {
    @return $target / $context * 1rem;
}

@function cr($target, $context: $root-font-size) {
    @return calc-rem($target, $context);
}
```

This is using `django-libsass`.

**Comment by asottile** [comment]
You'll want to report this on the upstream: sass/libsass

The upgrades we made in the 0.10.1 release were simply upgrading the version of libsass we use

That said, what does the caller look like?

**Comment by erbridge** [comment]
I see. I'm using `django-compressor` hooked up to use `django_libsass.SassCompiler` as a preprocessor. The relevant code is here:

https://github.com/torchbox/django-libsass/blob/8a525ef27ab52312a5bad22951094fe28217b0c8/django_libsass.py#L135

**Comment by asottile** [comment]
@erbridge can I clone this repository from somewhere?

**Comment by asottile** [comment]
Closing: the buh (if one exists) is in the upstream
