### ISSUE TITLE
why are source_comments forced to True when generating maps?

### ISSUE THREAD

**Issue by tisdall** [dahlia/libsass-python#124]
This is related to #94 as it's also about comments appearing in the compiled css.  I find it strange that when you request a `sourcemap` that the code forces comments on.  Is that necessary?

The lines in question:  https://github.com/dahlia/libsass-python/blob/python/sass.py#?L540-L541

The lines were added in fea52df but I can't really figure out why.  @dahlia, is it okay to remove that?

**Comment by asottile** [comment]
This is one thing I've been meaning to fix up since we'd like to use this feature as well.  I'm planning to see what the node / perl implementations do for source maps and emulate that here

**Comment by tisdall** [comment]
In the [perl implementation](https://github.com/sass/perl-libsass/blob/develop/bin/psass#L254) it seems it just has "source_comment" as a command line argument and uses whatever is passed in.  It seems to be completely independent of maps.

**Comment by tisdall** [comment]
^_^  I tried just commenting out the two lines I mentioned and it seems the .map file is now empty...  So, I guess I found the reason for the code.

**Comment by tisdall** [comment]
Ah..  found the problem in the C code:  https://github.com/dahlia/libsass-python/blob/13eb3f86399c93cb0240f3dc3b20a435b6a7d31c/pysass.cpp#L578

**Comment by tisdall** [comment]
I guess as a "TODO" it'd be nice to add a command line argument that set whether or not debugging comments are added.

**Comment by asottile** [comment]
Via #130

**Comment by asottile** [comment]
This is part of 0.11.0!
