### ISSUE TITLE
Move "python" branch to "master"

### ISSUE THREAD

**Issue by asottile** [dahlia/libsass-python#126]
This is mostly a question for @dahlia

Almost every time I make a feature branch my muscle memory kicks in and I `git checkout origin/master -b ...` which is incorrect for this repo.

I'm not sure `master` is being used for anything so I'm compelled to delete it.

And if I delete the current master, we might as well move `python` to `master`

What are your thoughts?

**Comment by dahlia** [comment]
There’s no reason to make `python` the default branch anymore, since we use submodule instead of forking libsass.

**Comment by asottile** [comment]
Sweet, I'll move this over once I'm at a terminal

**Comment by dahlia** [comment]
:+1:

**Comment by asottile** [comment]
ah, it seems I don't have permission to access the [Settings] menu, you'll have to do this one @dahlia :)

**Comment by dahlia** [comment]
@asottile Done! Now `master` is our new default branch.

**Comment by asottile** [comment]
I think travis-ci may be confused after this -- could you poke it? (I don't have admin there I don't think)

**Comment by dahlia** [comment]
I will look into this soon.

**Comment by dahlia** [comment]
Seems now it’s working.

**Comment by asottile** [comment]
Thanks! didn't think to look at .travis.yml -- womp!
