### ISSUE TITLE
Custom functions?

### ISSUE THREAD

**Issue by mxdubois** [dahlia/libsass-python#13]
Is it possible to add custom functions or provide a custom evaluation context as in the ruby version?
http://sass-lang.com/documentation/Sass/Script/Functions.html#adding_custom_functions

I need to inject some variables when I compile my scss.

**Comment by asottile** [comment]
I'm going to poke at this today.  We'd need this to replace pyscss at Yelp.

Here's reference material I'm going to be hacking from:
- https://github.com/sass/libsass/issues/514
- https://github.com/sass/perl-libsass/blob/master/lib/CSS/Sass.xs#L215
- https://github.com/sass/libsass/wiki/Custom-Functions-internal
