### ISSUE TITLE
Trouble with char escaping and interpolation

### ISSUE THREAD

**Issue by sveetch** [dahlia/libsass-python#135]
I was trying to compile this stylesheet https://github.com/divio/djangocms-admin-style/blob/master/djangocms_admin_style/sass/djangocms-admin.scss using libsass-python "0.10.1" and the webfont icons are broken in resulted CSS.

The problem come from here: https://github.com/divio/djangocms-admin-style/blob/master/djangocms_admin_style/sass/components/_iconography.scss#L261

For each icon content, the unicode char compile to a double slashed value like this:

```
.cms-icon-archive:before {
  content: "\\E001";
}
```
I saw some issues like #73 or other on libsass project almost related to my bug, but none of them resulted in double slashed value. 

Note that the original CSS compiled from 'djangocms-admin-style' developers are fine and they use node libsass.

I tried the same code with LibSass v3.3.2 (using SassMeister site) and the result is fine also: http://www.sassmeister.com/gist/5e531638b18838b89960

So i came back here to see if it would be a bug related to libsass-python, or did i miss something ?

Finally, i would note that i finded a quickfix to this bug replacing:
```
        content: #{"\"\\"}#{icon-char($filename) + "\""};
```

with:

```
        content: #{'\"\\' + icon-char($filename) + "\""};
```

That result to something like:

```
.cms-icon-archive:before {
  content: "\E001";
}
```

**Comment by asottile** [comment]
This is almost certainly a bug in the upstream (a regression) introduced between 3.3.2 and 3.3.3

Can you try against (our version) 0.10.0 (which uses 3.3.2)?

If it works in 0.10.0, please create a bug here: https://github.com/sass/libsass

**Comment by sveetch** [comment]
Thanks, you are right, i uninstalled 0.10.1, installed the 0.10.0, removed my fix then compile and finally the attempted result is correct:

```
.cms-icon-archive:before {
  content: "\E001";
}
```

I'm making an issue to libsass linking to this one.
