### ISSUE TITLE
'module' object has no attribute 'compile'

### ISSUE THREAD

**Issue by adamlwgriffiths** [dahlia/libsass-python#137]
I'm running Python 2.7.10 on Ubuntu 14.04 via Anaconda.

Running the example code I come across this.

```
$ pip freeze | grep libsass
libsass==0.10.1
$ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import sass
>>> sass.__version__
'2.2+libsass1.0.1'
>>> print sass.compile(string='a { b { color: blue; } }')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'compile'
>>> print sass.compile_string('a { b { color: blue; } }')
a b {
  color: blue; }
>>> dir(sass)
['CompileError', 'SASS_STYLE_COMPACT', 'SASS_STYLE_COMPRESSED', 'SASS_STYLE_EXPANDED', 'SASS_STYLE_NESTED', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__test__', '__version__', 'compile_file', 'compile_string']
```

I find the `__version__` value quite strange.

This is even more bizarre because the sass.py has the function `def compile(**kwargs)` in it.
```
$ cat ~/.anaconda/envs/systema/lib/python2.7/site-packages/sass.py | grep "def compile("
def compile(**kwargs):
```

This is also quite strange
```
>>> help(sass)
<snip>
FILE
    /home/adamgriffiths/.anaconda/envs/systema/lib/python2.7/site-packages/sass.so
<snip>
```
I would have expected that to be `sass.py`, `.pyc`, or `.pyo`

**Comment by asottile** [comment]
This doesn't look like our module at all.  Can you reproduce in an empty environment?

**Comment by asottile** [comment]
I think you've accidentally also installed https://github.com/rsenk330/pylibsass/blob/master/setup.py (which is out of date, and provides the same module name as we do for our c bits)

Uninstalling both and reinstalling `libsass` should fix the problem

**Comment by adamlwgriffiths** [comment]
Thanks for the tip.
Turns out I had a library called `sass` shadowing libsass. I must've installed it a while ago.

```
$ pip freeze | grep sass
libsass==0.10.1
sass==2.3
```

Removing it fixed the problem.
Thanks again.
