### ISSUE TITLE
Libsass version

### ISSUE THREAD

**Issue by sveetch** [dahlia/libsass-python#140]
It would be nice to have an additional module variable like __version__ but for the libsass library version, not the libsass-python version.

I'm integrating libsass-python in a project and the libsass-python will not talk to everyone on the libsass implementation.

Actually i don't find anything exposing the version for libsass library included.

**Comment by asottile** [comment]
This is part of 0.11.0!

**Comment by sveetch** [comment]
Nice, thanks to the team
