### ISSUE TITLE
compile error when running in tox environment?

### ISSUE THREAD

**Issue by cltrudeau** [dahlia/libsass-python#147]
I'm stuck.  I'm not sure it is even your library causing my issue, but don't know what else to do.  
I'm writing a package that uses libsass and django.  I have unit tests that run fine outside of tox.  For some reason though, when I try to test within tox (which just calls the same tests) I get a CSS compile error:

`sass.CompileError: Error: Invalid CSS after '.../3.3.5/fonts/";': expected 1 selector or at-rule, was "{}"`

The line that it is mentioning is an import line, so the actual problem could be buried far deeper.  I get the error in tox across several platforms, but it is definitely happening in the same python 3.4 / django 1.8 environment that I run the successful unit tests in.

I've put in a bunch of print statements looking for path errors and the like but have had no luck.

Any thoughts on what might be causing the issue?  Any hints as to where I can stick some debug in the library to further hunt this down?

Thanks for any help you can give.

**Comment by asottile** [comment]
One difference between tox and not is tox blanks your environment.  You could try setting `passenv=*` in your tox environment maybe?  If that works you could use a script like this to pinpoint the required environment variables: https://github.com/asottile/scratch/blob/183f97f358c3fcb977fd60493c30d19f21779e1e/python/minimal_environment.py

**Comment by asottile** [comment]
Another thing to check would be the version of libsass-python you're using in/out of tox (`.tox/py34/bin/pip freeze | grep libsass`)

**Comment by cltrudeau** [comment]
Thanks for the idea, unfortunately that didn't fix it.  I've switched to testing using the virutalenv that tox sets up but running it in the shell and it is still failing.

**Comment by cltrudeau** [comment]
Yep, that did it -- it was the version.  My setup file had a >= instead of a == in it and so I was getting a much newer version of the library in my tox environment.

Thanks.  That gives me a great short term fix.  

The bigger question then would be: what changed between 0.8.3 and 0.11.0 that would cause the file to stop compiling?  It is the simplest 2-line file in the world that imports Bootstrap -- so there must be something in Bootstrap 3.3.5 that won't compile using libsass 0.11.

**Comment by asottile** [comment]
The main major changes are in the upstream.  0.8.3 used 3.2.5, and 0.11.0 uses 3.3.4

That said, I was able to compile bootstrap (retrieved from https://github.com/twbs/bootstrap-sass/archive/v3.3.5.tar.gz):

```
$ cat test.scss
@import "bootstrap";
$ sassc -I pkg/bootstrap-sass-3.3.5/assets/stylesheets/ test.scss testout.css
$ echo $?
0
$ head -n 10 testout.css 
@charset "UTF-8";
/*!
 * Bootstrap v3.3.5 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
/*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
html {
  font-family: sans-serif;
  -ms-text-size-adjust: 100%;
```

**Comment by cltrudeau** [comment]
OK, thanks. I'll dig in later to see what is causing my problem. In the
meantime, 8.3 works for what I need.

Thanks for being so responsive.
...ct

**Comment by asottile** [comment]
No problem!
