### ISSUE TITLE
Slooooow Compiling

### ISSUE THREAD

**Issue by samuelcolvin** [dahlia/libsass-python#150]
I've found compiling libsass-python to be very slow to compile. "Very" is a useless work description I know, but it's slower than any other library I'm using. I can give more details on timing etc. if required.

This is on Ubuntu: 15.10 Desktop, 16.04 Desktop and the Heroku cedar-14 stack which is based on 14.04 server.

Is there any possibility compiling performance could be improved? If there's a particular piece of work required I'd be happy to contribute.

**Comment by asottile** [comment]
Unfortunately not.  We build libsass from source.  Setuptools doesn't really provide a simple way to speed this up. There's hacks to make a parallel build but I don't think the complexity is worth it.  I'd suggest using something which caches the wheel such as pip>=8 or https://github.com/yelp/venv-update

**Comment by asottile** [comment]
You could also pre build a wheel on a compatible platform and install from that (pip wheel libsass) (pip install libsass*.whl)

**Comment by samuelcolvin** [comment]
Do you think it would be possible to add a precompiled distribution for 64bit linux? It must be quite a cohort of installs and would speed up install a lot.

**Comment by asottile** [comment]
Pypi doesn't allow uploading of 64bit Linux wheels except for manylinux which we're not compatible with due to the libraries linked.   I could upload one, but it'd be unlikely to work on anything that isn't my exact configuration.  The linux_x86_64 situation is kind of unfortunate :(

**Comment by asottile** [comment]
Actually seems I was wrong, manylinux seems to work for libsass-python (I was trying on a too-new version of libc6).   I'll make a script to upload these.
