### ISSUE TITLE
Drop python2.6?

### ISSUE THREAD

**Issue by asottile** [dahlia/libsass-python#157]
Python2.6 had been end of life for [~3 years](https://www.python.org/dev/peps/pep-0361/), our master build is currently failing because `flake8` has dropped support.  I think we probably should as well? (or at least stop testing against it?)

**Comment by dahlia** [comment]
It'd be better to stop linting against 2.6 whether we drop 2.6 support or not.

**Comment by dahlia** [comment]
There's no strong reason to support 2.6.  When I started the project, popular Python libraries supported 2.6, so I decided to support 2.6 too.  I've never used 2.6 for about 6 years. I think it's okay to drop 2.6 support now.

**Comment by asottile** [comment]
+1, I'll remove explicit 2.6 support
