### ISSUE TITLE
compiler get error when using unitless or unit functions

### ISSUE THREAD

**Issue by cairabbit** [dahlia/libsass-python#159]
I had a scss function defined as below:
```scss
@function is-number($value) {
  @return type-of($value) == 'number' and unitless($value);
}
```

The function would cause python getting an interruption and popup a window asking to debug or stop it. 
It works good without unitless calling. 
I'm using python 3.4.4, libsass 0.11.1.

I'm not sure if this is a bug or it just happened on my machine. Could anyone help? Thanks in advance.

**Comment by asottile** [comment]
Not at a computer (or a windows machine) at the moment.  Could you provide some sample usage (a call maybe? ).

**Comment by asottile** [comment]
At least on linux, this code seems to work fine:

```scss
@function is-number($value) {
  @return type-of($value) == 'number' and unitless($value);
}
@debug(is-number(5));
@debug(is-number(5px));
@debug(is-number(hello));
```

```
$ ./venv/bin/sassc test.scss /dev/stdout
/home/asottile/workspace/libsass-python/test.scss:4 DEBUG: true
/home/asottile/workspace/libsass-python/test.scss:5 DEBUG: false
/home/asottile/workspace/libsass-python/test.scss:6 DEBUG: false
```

**Comment by asottile** [comment]
Seems to work for me on windows with python 3.4.4 as well:

```
IEUser@IE11WIN10 MINGW64 /tmp/foo
$ ./venv/Scripts/sassc.exe test.scss
C:/Users/IEUser/AppData/Local/Temp/foo/test.scss:4 DEBUG: true
C:/Users/IEUser/AppData/Local/Temp/foo/test.scss:5 DEBUG: false
C:/Users/IEUser/AppData/Local/Temp/foo/test.scss:6 DEBUG: false
```

**Comment by asottile** [comment]
@cairabbit any updates?

**Comment by asottile** [comment]
Closing for now, if you have more details please reopen :)
