### ISSUE TITLE
Consistent line endings between platforms

### ISSUE THREAD

**Issue by rbu** [dahlia/libsass-python#160]
We're using libsass-python to compile SCSS on different platforms. Unfortunately, on Windows systems the generated CSS contains windows line endings while on Linux systems, Linux line endings are used.

This creates a problem where unnecessary whitespace changes make reviews harder.

I would suggest either using one set of endings consistently (Linux, for example) OR analyzing the file endings of the input file and sticking with those.

**Comment by asottile** [comment]
We're a very simple wrapper around the underlying `libsass` c++ library.  I don't think we control the line endings at all but I'll check :)

**Comment by asottile** [comment]
So it seems that the underlying libsass library is *always* going to hand us unix line endings:

```python
# This is on windows
>>> import sass
>>> sass.compile(string='a\n{b: c;\n}')
u'a {\n  b: c; }\n'
>>> sass.compile(string='a\r\n{b: c;\r\n}')
u'a {\n  b: c; }\n'
>>> sass.compile(string='a\r{b: c;\r}')
u'a {\n  b: c; }\n'
```

The difference happens when the files are written out to disk:

```python
# Again, on windows
>>> with open('f', 'w') as f:
...     f.write('foo\nbar\n')
...
>>> io.open('f', newline='').read()
u'foo\r\nbar\r\n'
```

You'll notice that `open` is silently rewriting our unix line endings (`\n`) to windows line endings (`\r\n`).

I'm of the opinion that we shouldn't be allowing that (after all, we're a simple wrapper!).

Given the node-sass behaviour:

```
# Yep, still on windows
$ ./node_modules/.bin/node-sass test1.scss test1.css
Rendering Complete, saving .css file...
Wrote CSS to C:\Users\Anthony\Desktop\git\libsass-python\test1.css
$ python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> io.open('test1.css', newline='').read()
u'a {\n  b: c; }\n'
```

I think we should be also preserving unix line endings.

**Comment by asottile** [comment]
Here's a PR which solves this: https://github.com/dahlia/libsass-python/pull/161

**Comment by rbu** [comment]
@asottile, thanks so much for the quick analysis and fix. Much appreciated.

**Comment by jensenhwa** [comment]
Shall we update the documentation example with this fix, for writing a single sass file?

I believe [this section](https://sass.github.io/libsass-python/#compile-a-directory-of-sass-files-to-css) should add `encoding='utf-8', newline=''` on the first `open()` call.

**Comment by asottile** [comment]
I don't think the docs need updating, the example there is fine (and it's not really our responsibility to teach about `open`) -- the consumer can choose to handle newlines however they want and the simpler the example the better imo.  This particular issue was about the libsass-python api which wrote to disk, which has been fixed.
