### ISSUE TITLE
Support for creating sourcemaps when using dirname parameter in sass.compile?

### ISSUE THREAD

**Issue by benpatterson** [dahlia/libsass-python#162]
When I attempt to create sourcemaps when compiling a nested scss directory, I get an error pointing out that filename is required. However, I need to compile a directory rather than one file.

It's possible I'm asking for an enhancement; it's possible I'm not using the method correctly...I'll be curious either way. Thanks for the help!

More info:

My call is like this:
```python
sass.compile(
                dirname=(sass_source_dir, css_dir),
                include_paths=lookup_paths
                source_comments=True,
                output_style='nested',
                source_map_filename=my_source_map
            )
```

Output/exception is:
```
  File "my_venv/sass.py", line 523, in compile
    raise CompileError('source_map_filename is only available with '
CompileError: source_map_filename is only available with filename= keyword argument since it has to be aware of it
```

**Comment by asottile** [comment]
So usually you need one sourcemap per compiled scss file.  When compiling a directory there may be many source files that get compiled.  The kwarg only allows for a single output source map filename.  This wouldn't really work for multiple compiled scss files as they'd clobber each other and the last one would win.

**Comment by benpatterson** [comment]
Ah ok. Thanks for explaining, @asottile .
