### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by rbu** [dahlia/libsass-python#163]
I appreciate that #161 was merged, but unfortunately we cannot depend on it as it's not released yet. Is there a roadmap for when releases are created?

**Comment by asottile** [comment]
We tend to schedule our releases around when the upstream makes a major change (unless of course we fix some critical bug on our side).  They haven't released in quite a while but it looks like they're in the somewhat-final stages of the 3.4.0 release: https://github.com/sass/libsass/issues/2174

**Comment by asottile** [comment]
upstream 3.3.6 is now available as 0.11.2! :sparkles:
