### ISSUE TITLE
Follow upstream's version

### ISSUE THREAD

**Issue by dahlia** [dahlia/libsass-python#164]
Besides #163, it would be more predictable if libsass-python's version follows upstream libsass' version.  Since we need to bump version when we fix our own bugs, we should follow only major and minor versions.

Opinions?

**Comment by asottile** [comment]
Here's my opinions on this: https://github.com/dahlia/libsass-python/issues/154#issuecomment-224347605

I think it would be more confusing if we only followed two (or even one) of their version numbers and not all three (especially when giving bug reports upstream).  And then it would be difficult for us to communicate breaking / feature changes in our own api.

Perhaps the most popular binding (node-sass) doesn't seem to follow versions either: https://github.com/sass/node-sass/releases

**Comment by dahlia** [comment]
🤔 Okay, this versioning way indeed seems several confusion as well to users.
