### ISSUE TITLE
Sassy SASS Can Not Be Loaded as a String

### ISSUE THREAD

**Issue by tmose1106** [dahlia/libsass-python#169]
Hello, I'm not sure if this is a known fault, or perhaps purposeful design, but I have found that when inputting sassy sass into the compile function using a string, I receive a failure, but scss sass works just fine. I attempted to make an example in the picture below.

![1477761647](https://cloud.githubusercontent.com/assets/15310560/19831550/8ec4dfee-9dda-11e6-8d28-a0b89ce951df.png)

I have also tested this using the filename thinking perhaps the library could only read scss, but that appears to not be the case. Sassy and scss formatted files work just fine. I have also looked at the documentation briefly, but didn't see anything about reading sassy sass differently. So, can anything be done about this?

P.S., I am using python 3.5.2 and libsass 0.11.1 according to pip.

**Comment by asottile** [comment]
So looking at the api, this could be configurable though we currently don't expose a way to set this option. 

https://github.com/sass/libsass/blob/bf7d830377152310e7e5cbfb74bb9884ff32c5a8/include/sass/context.h#L100

**Comment by asottile** [comment]
oh actually we do expose this (was just looking through our tests)

```python
>>> sass.compile(
...     string='''\
... a
...     color: red
... ''',
...     indented=True,
... )
u'a {\n  color: red; }\n'
```

**Comment by vlad1777d** [comment]
@asottile , hello, could you also add it somewhere into documentation ?
I read docs on website, also read `compile` function, but could not find this solution, only found it here.
I spent enough much time for it.

Thank you.

**Comment by asottile** [comment]
@vlad1777d appears to be documented here: https://sass.github.io/libsass-python/sass.html#sass.compile

> **_indented_ (bool)** – optional declaration that the string is Sass, not SCSS formatted. `False` by default

if there's a place you'd like to see it more prominently featured, I'd suggest proposing a PR

**Comment by vlad1777d** [comment]
@asottile , I think, it just could be added to readme into Examples section.

### Examples

#### Compile SCSS:
```python
import sass
print sass.compile(string='a { b { color: blue; } }')
>>>   a b {
     color: blue; }
```
#### Compile Sass:
```python
import sass
print sass.compile(string='''
a b
    color: blue
''', indented=True)
>>>   a b {
     color: blue; }
```

**Comment by asottile** [comment]
Please propose a PR, would be happy to take an example!
