### ISSUE TITLE
Wheel on PyPi

### ISSUE THREAD

**Issue by ar4s** [dahlia/libsass-python#171]
Can you upload (by ``python setup.py sdist bdist_wheel upload``) ``.whl`` to PyPi after merge #170?

**Comment by asottile** [comment]
We already provide wheels for windows and manylinx.  You can find the supported ones here:

https://pypi.python.org/pypi/libsass/0.11.2

You need a sufficiently new version of pip to take advantage of manylinux wheels (>8)

**Comment by ar4s** [comment]
@asottile thanks!
