### ISSUE TITLE
Segmentation fault with foundation-sites-6.3.0

### ISSUE THREAD

**Issue by cblegare** [dahlia/libsass-python#177]
- `libsass-python==0.12.2`
- `cpython==3.5`
- `uname==Linux forty-two 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux`

```
[New LWP 18011]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `python setup.py build_sass'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  Sass::Pseudo_Selector::operator< (this=0x154c510, rhs=...) at libsass/src/ast.cpp:706
706   libsass/src/ast.cpp: Aucun fichier ou dossier de ce type.
```

Notes:

- `python setup.py build_sass` above is not the same as libsass-python setuptools integration.
- _Aucun fichier ou dossier de ce type_ translates to *No such file or directory*

I've had this segmentation fault building sources from Zurb Foundation (`foundation-sites-6.3.0`), given the following source scss content:

```
@import 'foundation';

@include foundation-grid; // This include is involved in the crash
```

(Other `@includes` from foundation build fine)

Should I open this issue on https://github.com/sass/libsass instead?

**Comment by asottile** [comment]
Ah yes I'd suggest an upstream report (as I see you've made!) -- we're generally a pretty simple wrapper (though we occasionally have our bugs too).  The stack points to the upstream code :)

Thanks for the report!
