### ISSUE TITLE
Test, build, and support python3.6

### ISSUE THREAD

**Issue by asottile** [dahlia/libsass-python#180]
3.6 is out!  We should test against it (by modifying .travis.yml, appveyor.yml, tox.ini) and release against it (need to modify `build_manylinux_wheels.py`) and declare we support it `setup.py`

Should we stop building against python3.4?  I think it's reasonable to support python2.7 + the last two python3 releases -- does that seem reasonable (we don't have any version-specific patches for python3 anyway)?

**Comment by dahlia** [comment]
Unless we need any feature Python 3.4 doesn't provide, I'd like to support Python 3.4+. I still maintain some private projects using 3.4 at work.  Upgrading these project to 3.5 or 3.6 is possible though.

**Comment by frostbtn** [comment]
> Should we stop building against python3.4?
That's one frightening proposal. Debian Linux has only 3.4 at the moment, and will include 3.5 no earlier than February, and 3.6 is (probably) somewhere in 2019 :)

If it's not involve too much hustles, please, keep 3.4 for 2017.

**Comment by asottile** [comment]
Sounds good, I'll keep python3.4 for now :)

**Comment by asottile** [comment]
Is it reasonable to drop python3.3 from testing?  We don't provide releases for it

**Comment by dahlia** [comment]
3.3 is felt too old to me. 🤔
