### ISSUE TITLE
Cannot install on Cygwin; pysass.cpp doesn't compile

### ISSUE THREAD

**Issue by chaosdeathfish** [dahlia/libsass-python#195]
Attempting to install libsass-python on Cygwin fails to run; it instead displays errors:

```
In file included from /usr/include/python3.4m/Python.h:8:0,
                 from pysass.cpp:2:
/usr/include/python3.4m/pyconfig.h:1440:0: warning: "__BSD_VISIBLE" redefined
 #define __BSD_VISIBLE 1
 ^
In file included from /usr/include/sys/config.h:5:0,
                 from /usr/include/_ansi.h:16,
                 from /usr/include/string.h:10,
                 from pysass.cpp:1:
/usr/include/sys/features.h:250:0: note: this is the location of the previous definition
 #define __BSD_VISIBLE  0
 ^
In file included from /usr/include/python3.4m/pyport.h:335:0,
                 from /usr/include/python3.4m/Python.h:50,
                 from pysass.cpp:2:
/usr/include/sys/time.h:104:34: error: ‘u_int’ has not been declared
 bintime_mul(struct bintime *_bt, u_int _x)
                                  ^
pysass.cpp: In function ‘Sass_Import** _call_py_importer_f(const char*, Sass_Importer_Entry, Sass_Compiler*)’:
pysass.cpp:464:55: error: ‘strdup’ was not declared in this scope
         if (source_str) source_str = strdup(source_str);
                                                       ^
pysass.cpp:465:64: error: ‘strdup’ was not declared in this scope
         if (sourcemap_str) sourcemap_str = strdup(sourcemap_str);
                                                                ^
pysass.cpp: In function ‘PyObject* PySass_compile_string(PyObject*, PyObject*)’:
pysass.cpp:530:51: error: ‘strdup’ was not declared in this scope
     context = sass_make_data_context(strdup(string));
                                                   ^
error: command 'gcc' failed with exit status 1
```

It appears that Cygwin's gcc doesn't define strdup from strings.h when in -std=c++0x mode. Using -std=gnu++0x this all compiles fine. Using the same version of gcc (5.4.0) on Ubunutu works fine.

**Comment by chaosdeathfish** [comment]
https://github.com/chaosdeathfish/libsass-python/commit/1f82fce931f0e6a215b3881401a8f1b250de54ff fixes this issue

**Comment by asottile** [comment]
I think I can change this to not rely on strdup at all.  sass itself provides an implementation that should _probably_ be used (since they call `delete[]` on the result anyway).

If I make a branch, can you try it out for me?

**Comment by chaosdeathfish** [comment]
Sure, I'll be happy to give it a go! Fixing it properly does seem preferable to my rather hacky fix.

**Comment by asottile** [comment]
Can you try this branch for me? https://github.com/dahlia/libsass-python/pull/196

**Comment by chaosdeathfish** [comment]
Unfortunately that doesn't seem to work, due to strdup use within libsass itself:
```
libsass/src/sass_functions.cpp: In function ‘Sass_Function* sass_make_function(const char*, Sass_Function_Fn, void*)’:
libsass/src/sass_functions.cpp:21:37: error: ‘strdup’ was not declared in this scope
     cb->signature = strdup(signature);
                                     ^
error: command 'gcc' failed with exit status 1
```

**Comment by asottile** [comment]
Strange!  I'm going to merge it either way, then we can probably ask upstream for some help here.  Worst case we'll apply your patch which seems fine to me :)

**Comment by asottile** [comment]
I wonder if just changing to always using `-std=gnu++0x` will fix this without breaking other compilers. I'll try that next!

**Comment by asottile** [comment]
Does this patch work? https://github.com/dahlia/libsass-python/pull/197

**Comment by chaosdeathfish** [comment]
That builds fine - I'll test it in more detail when I have a moment!

**Comment by chaosdeathfish** [comment]
The unit tests run fine, I'll hopefully have time to run it against some actual data later today but everything is looking good so far.

**Comment by asottile** [comment]
Hmm, I guess my main concern would be with osx.  I'll see if I can find someone to test on osx.

**Comment by asottile** [comment]
Had a friend at work try osx, seems good I'll merge this PR :D

**Comment by asottile** [comment]
Note that this is now part of a real release: 0.13.0

**Comment by saper** [comment]
`strdup()` is not a part of a C or C++ standard, so technically speaking Cygwin is right.
