### ISSUE TITLE
Publish Python 3.6 version for Windows on PyPI

### ISSUE THREAD

**Issue by AlekseiCherkes** [dahlia/libsass-python#198]
Hello!
Python 3.6 has been there for ages, but there is still no prebuld version for Windows on PyPI. 
There are wheel versions only for python 3.5.
On windows is very inconvenient to have a Visual C++ dependency during package install.
Do you have any plans on releasing new binaries for windows?

**Comment by asottile** [comment]
Yep, I can try and do this. we changed the build after the last release to include py36 but didn't upload the new wheels (oops!)

**Comment by asottile** [comment]
I've manually uploaded the wheels from this build: https://ci.appveyor.com/project/dahlia/libsass-python/build/385

**Comment by AlekseiCherkes** [comment]
It works. 
Thank you!
