### ISSUE TITLE
Add an extra install option to disable the compilation step

### ISSUE THREAD

**Issue by goanpeca** [dahlia/libsass-python#200]
@dahlia thanks for the package :-)

I am building conda packages for libsass (the C library and the CLI) and for libsass-python. Since with conda we dont need to include all the extra compilation steps (as conda will handle libsass standalone) would you be ok with adding an option for install so that it does not perform the compile steps? Something that would yield something like:

`python setup.py install-no-compile`

or

`python setup.py install --no-compile` 

I can make the PR

**Comment by asottile** [comment]
Our C binding is very tightly coupled to the exact version of libsass, splitting them apart is going to give you (and us) headaches :)

**Comment by goanpeca** [comment]
>Our C binding is very tightly coupled to the exact version of libsass, splitting them apart is going to give you (and us) headaches :)

Python was never meant to be used as a compile toolchain, but conda is. Anyway will try with https://github.com/pistolero/python-scss then. Thanks

**Comment by asottile** [comment]
You could try using the same approach the debian packaging uses: https://github.com/dahlia/libsass-python/issues/117

**Comment by goanpeca** [comment]
Actually https://github.com/pistolero/python-scss is much simpler, so I will stick to that one.

**Comment by asottile** [comment]
Good luck, they haven't updated in 3 years :)

**Comment by goanpeca** [comment]
>Good luck, they haven't updated in 3 years :)

Yep probably right....

What's the problem with this

>Our C binding is very tightly coupled to the exact version of libsass, splitting them apart is going to give you (and us) headaches

**Comment by asottile** [comment]
you'll run into this problem with any bindings of libsass (including the one you linked).  Since libsass changes rapidly (including breaking changes / new features / etc.), the versions of bindings and libsass itself will end up being tightly coupled.

For instance, the debian package needs to upgrade libsass and libsass-python in lockstep to ensure compatibility.

Curious why the manylinux wheels we already provide aren't sufficient for conda (or why conda can't just retag them for its purposes).

I'm mostly hesitant because there's already good solutions to the problem you're describing and it'll complicate our already very complicated setup.py -- but also because I think your solution is not a maintainable one.

**Comment by goanpeca** [comment]
It seems you are not familiar with conda.

**Comment by asottile** [comment]
No I understand conda, but that doesn't mean I agree with it :P

**Comment by goanpeca** [comment]
>No I understand conda, but that doesn't mean I agree with it :P

No comment... anyway

A conda package for libsass would be created with the specific version of libsass and built via https://github.com/conda-forge and hosted on anaconda.org/conda-forge so there would be a `libsass-X.X` living on the conda environment prefix upon installation `<PREFIX>/include/libsass....h`

Another conda package based on this repo named `libsass-python` would be created with the specific version that is currently supported and part of the recipe has as run dependencies the specific version of the conda libsass package (an exact pin) that needs to be used.

So I don't see how 

>you'll run into this problem with any bindings of libsass 

even applies...

**Comment by asottile** [comment]
You have to maintain a separate libsass / python-libsass and maintain the version parity between the two.  You've still failed to address my concern: why split them at all?

**Comment by asottile** [comment]
Also conda users can just use pip and get the prebuilt packages that we _already_ provide for various platforms.

**Comment by goanpeca** [comment]
>You have to maintain a separate libsass / python-libsass and maintain the version parity between the two.
>You've still failed to address my concern: why split them at all?

'Cause conda is a python agnostic package manager (that happens to be written in python), I could just as easily have R (libsass-r), Julia (libsass-julia), Perl (libsass-perl), Lua (libsass-lua) etc conda packages that would use and depend on the same (compatible) libsass package for whatever version they plan to support.


```

                    libsass-2.x                       libsass-3.x
                         |                                 |
                         |                                 |    
                        / \                               / \
                       /   \                             /   \
    libsass-python-X.Y    libsass-lua-J.K   libsass-python-Z.W    libsass-lua-O.P

**Comment by asottile** [comment]
But this works just fine:

```

                                                      libsass-3.x
                                                           |
                                                           |    
                                                          / \
                                                         /   \
    libsass-python-X.Y                     libsass-lua-J.K libsass-lua-O.P

**Comment by goanpeca** [comment]
All I am asking is adding this extra option (a big IF on `setup.py`) to avoid a patching that may break in the future and make things harder to maintain (on my side), on your side nothing will change besides that. If this is not possible, I will do the patch I guess...

**Comment by asottile** [comment]
You've again failed to address my question: What's wrong with the status quo?

**Comment by goanpeca** [comment]
>What's wrong with the status quo?

For web development that relies almost entirely on pure python modules with pip? Nothing.

For other things that involved compiled libraries besides pure python modules and such, well pip simply does not cut it, and hence why conda exists. I am just asking for a way to make this package easier to build and maintain within the conda ecosystem.

**Comment by asottile** [comment]
Why doesn't the existing build work in conda?

**Comment by goanpeca** [comment]
Cause in the conda ecosystem conda build and a recipe are in charge of creating the binaries, and its best to align the toolchain within the ecosystem.

**Comment by asottile** [comment]
And why can't the conda build recipe just call the existing supported build?

Personally I don't want to enable (and therefore have to support) the following:
- version mismatch
- a code pathway that we won't use and won't test

**Comment by goanpeca** [comment]
>version mismatch

That won't happen

>a code pathway that we won't use and won't test

Fine, I will patch the setup.py then

**Comment by asottile** [comment]
It won't happen in conda, but by enabling it through setup.py, people will do it elsewhere.
