### ISSUE TITLE
Disable coveralls comments on pull requests

### ISSUE THREAD

**Issue by asottile** [dahlia/libsass-python#206]
I find the comments to be quite annoying (and redundant, there's github status api for a reason!).

I don't have permission to turn them off though, @dahlia if you agree could you untick the checkbox on coveralls?  It looks something like this (in the settings tab for the repository):

![](https://i.fluffy.cc/xqjF57qTRpMnqql9xx8xCdPB6FRLhJtf.png)

**Comment by dahlia** [comment]
Disabled leaving comments.  😄
