### ISSUE TITLE
Invalid submodule(libsass) commit

### ISSUE THREAD

**Issue by gastlich** [dahlia/libsass-python#213]
Hello there,
in the beginning I would like to thank you for maintaining this repo... I'm a bit concerned about commit used for libsass submodule, which doesn't exist anymore in libsass's master
https://github.com/sass/libsass/tree/31573210c0d120ae56aaea543a0dbab5255cdfb7

https://github.com/sass/libsass/commits/master

**Comment by asottile** [comment]
We're still tracking the `3.4.x` set of releases.  `sass/libsass`'s `master` branch is their `3.5` beta branch

```
$ git describe 31573210c0d120ae56aaea543a0dbab5255cdfb7 --tags
3.4.5
```

**Comment by asottile** [comment]
Closing as this is as-intended.
