### ISSUE TITLE
Sass color functions are not case insensitive

### ISSUE THREAD

**Issue by SamyCookie** [dahlia/libsass-python#214]
```
In [12]: sass.compile(string='a { b { color: lighten(crimson, 10%); } }')
Out[12]: u'a b {\n  color: #ed365b; }\n'
```
But if you use uppercase letters in colors (allowed by CSS specification), it fails :
```
In [13]: sass.compile(string='a { b { color: lighten(Crimson, 10%); } }')
---------------------------------------------------------------------------
CompileError                              Traceback (most recent call last)
<ipython-input-13-2066632bd1a9> in <module>()
----> 1 sass.compile(string='a { b { color: lighten(Crimson, 10%); } }')

/usr/local/lib/python2.7/dist-packages/sass.pyc in compile(**kwargs)
    638         raise TypeError('something went wrong')
    639     assert not s
--> 640     raise CompileError(v)
    641 
    642 

CompileError: Error: argument `$color` of `lighten($color, $amount)` must be a color

       Backtrace:
        stdin:1, in function `lighten`
        stdin:1
        on line 1 of stdin
>> a { b { color: lighten(Crimson, 10%); } }
   ---------------^
```
Sass Ruby version is working well with some uppercase syntax.

**Comment by asottile** [comment]
Our library is just a simple wrapper around [libsass](https://github.com/sass/libsass) -- in this case, the upstream functions the same way, if you believe this is a bug please open a bug on the upstream.

fwiw, it appears [this](https://github.com/sass/libsass/blob/4f74571d78d738ea5489d588550a26c81a45164b/src/color_maps.hpp#L18) is the list of colors.

Interestingly, ruby-sass permits case insensitive colors:

```
$ sass test.scss
a b {
  color: #ed365b; }
```

So this is probably a bug with `libsass` itself -- I'll look into making an issue on the upstream

**Comment by asottile** [comment]
I've created an upstream bug here:

https://github.com/sass/libsass/issues/2462

Feel free to follow that issue :)

**Comment by SamyCookie** [comment]
Got it. Thanks for the response !

**Comment by asottile** [comment]
I believe 0.13.3 has a fix for this!
