### ISSUE TITLE
Problems with packaging for Fedora

### ISSUE THREAD

**Issue by Traceur759** [dahlia/libsass-python#217]
I am trying to package this for Fedora. I would like to ask about following two subjects:
1) Would it be possible to include the LICENSE file into tarballs? I'd like to package it within the RPM.
2) I found some complications when it came to using system-installed libsass. I had to make a patch for it, so it linked against the system one. What about implementing some environment variable that would make it easier to tell setup.py whether to link against bundled or system libsass?

**Comment by asottile** [comment]
I believe #216 solves 1, it has yet to be included in a release yet however

For 2. you could probably leverage the patch that [the debian packaging uses](https://github.com/dahlia/libsass-python/issues/117#issuecomment-171381930)

**Comment by Traceur759** [comment]
Found out one more thing. In Fedora, the sassc executable conflicts with a ruby package that provides the same named executable.
Does it make sense to keep both sassc and sassc.py executables?
If yes, would you be willing to rename the no-suffix executable? (sassc)

**Comment by asottile** [comment]
I'd actually like to rename it to `pysassc`, that's covered here: #134

**Comment by asottile** [comment]
I've just merged a pull request which adds `pysassc`, feel free to omit `sassc` in the fedora packaging

**Comment by Traceur759** [comment]
Awesome!
Will that be included in a release anytime soon?
It is not good practice to make packages from the repo itself.

**Comment by asottile** [comment]
I plan to make a release today -- I'll update here when I'm done with that

**Comment by asottile** [comment]
This is now in 0.13.3!

**Comment by asottile** [comment]
@Traceur759 is this done now?

**Comment by Traceur759** [comment]
Yes, you may close this now.
The package itself is going to take some more time, since I am paying attention to other matters, currently.
