### ISSUE TITLE
libsass-0.5.1-cp27-none-win32.whl Fails to install on Windows 8.1

### ISSUE THREAD

**Issue by flavour** [dahlia/libsass-python#28]
I am running Windows 8.1 64-bit.
I always run Python 2.7 in 32-bit mode
I installed libsass both via PIP & via the downloaded wheel.
Both times it fails in the same way when I try to import sass:
>>> import sass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\bin\python27\lib\site-packages\sass.py", line 21, in <module>
    from _sass import (OUTPUT_STYLES, SOURCE_COMMENTS, compile_dirname,
ImportError: DLL load failed: The specified module could not be found.

_sass.pyd is present in the same folder as sass.py

I don't have any Visual Studio to try & compile a version myself.
Are there any Win32 libs which I need installing on my system to get this working?

**Comment by demidov91** [comment]
The same error on python3.3 and 3.4, windows 7 (32bit)

**Comment by pakal** [comment]
Just had the same problem, on a python3.4 (32bits) on a win7-64bits OS.

Dependency Walker showed that "_sass.pyd" needed VCRUNTIME140.DLL and some other DLLs.

In  the end, just install the small "Visual C++ Redistributable for Visual Studio 2015" to get that bunch of missing C++ components. No need to install the 11+ GB of Visual Studio Suite. ^^

**Comment by demidov91** [comment]
Ended up by installing pyScss...

**Comment by asottile** [comment]
Seems we can probably fix this with: http://stevedower.id.au/blog/building-for-python-3-5-part-two/

**Comment by asottile** [comment]
This is fixed in 0.9.3, I'll upload the windows wheels once appveyor finishes

**Comment by asottile** [comment]
The wheels should be there now
