### ISSUE TITLE
Trouble Installing 0.6.0 on Travis CI

### ISSUE THREAD

**Issue by clintonb** [dahlia/libsass-python#31]
pip installs on Travis are failing for 0.6.0. 0.5.1 works. You can view the full output at https://travis-ci.org/edx/edx-analytics-dashboard/builds/39157543. The error messages have been copied below.

```
pip install -q -r requirements/base.txt --exists-action w
  Could not find a tag or branch '0d7847f9dfa2281640527b4dc51f5854f950f9b7', assuming commit.
  Could not find a tag or branch 'd45d0bd8d64c69531be69178b9505b5d38806ce0', assuming commit.
Command /home/travis/virtualenv/python2.7.8/bin/python -c "import setuptools, tokenize;__file__='/home/travis/virtualenv/python2.7.8/build/libsass/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mfLxMF-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python2.7.8/include/site/python2.7 failed with error code 1 in /home/travis/virtualenv/python2.7.8/build/libsass
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.8/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
make: *** [requirements] Error 1
```

**Comment by Navajyoth** [comment]
I got follwing error while using "pip install libsass"  in ubuntu 15.04
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/rawdata/Envs/aws/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-5WzZUz/libsass/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NGsUDi-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/rawdata/Envs/aws/include/site/python2.7 failed with error code 1 in /tmp/pip-build-5WzZUz/libsass
Traceback (most recent call last):
  File "/home/rawdata/Envs/aws/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/rawdata/Envs/aws/local/lib/python2.7/site-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/home/rawdata/Envs/aws/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)

**Comment by asottile** [comment]
@Navajyoth 

This is what I get on a clean 15.04 install (with pip from apt and virtualenv from pip)

```
$ virtualenv venv && . venv/bin/activate && pip install libsass
[[ snip ]]
    pysass.cpp:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/home/asottile/venv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-PV5hzR/libsass/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-W4Vise-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/asottile/venv/include/site/python2.7/libsass" failed with error code 1 in /tmp/pip-build-PV5hzR/libsass
```

But after `sudo apt-get install python-dev`:

```
$ pip install libsass
Collecting libsass
  Using cached libsass-0.8.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in ./venv/lib/python2.7/site-packages (from libsass)
Installing collected packages: libsass
  Running setup.py install for libsass
Successfully installed libsass-0.8.0
```

**Comment by Limeth** [comment]
@Navajyoth Thank you, that helped me.
