### ISSUE TITLE
Support indented syntax for string input

### ISSUE THREAD

**Issue by tomxtobin** [dahlia/libsass-python#41]
libsass supports the [indented syntax](http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html), e.g.,
```sass
p
  a
    color: blue
```
This binding correctly handles files written in the indented syntax if passed as filenames with the `.sass` extension, e.g.,
```python
sass.compile(filename="foobar.sass")
```
... but has no support for the indented syntax as string input, e.g.,
```python
sass.compile(string="p\n  a\n    color: blue\n")
```
Perhaps a keyword parameter, e.g., `syntax="sass"` / `syntax="scss"`?

**Comment by asottile** [comment]
The setting in libsass's context is `is_indented_syntax_src` if you're interested in taking a shot at it :)
