### ISSUE TITLE
More feedback on the compilation process - suggestion

### ISSUE THREAD

**Issue by flaker** [dahlia/libsass-python#42]
Hi,

The guy using sass on my team asked me yesterday if there was a flag or something so he can just be watching the Flask console to see if something failed while changing his sass files instead of going to the generated file to see details on the exception. I couldn't find any and ended up adding:

    print '*' * 80
    print repr(e)
    print '*' * 80

inside `SassMiddleware.__call__` to get any exception info from any `CompileError`. This is absolutely raw but seems to be useful.

Maybe something nicer can be added, like a parameter to send errors to stderr or something like that.

Thanks,

Federico

**Comment by dahlia** [comment]
It would be implemented using `logging` module.  I will consider this!  Thanks.
