### ISSUE TITLE
Cut 0.7.0 release

### ISSUE THREAD

**Issue by asottile** [dahlia/libsass-python#47]
:)

**Comment by bardo** [comment]
Seconded :)

**Comment by felipecabargas** [comment]
+1 here

![giphy](https://cloud.githubusercontent.com/assets/1175479/6340710/e8595cce-bba0-11e4-816a-9dfde1aba1e4.gif)

**Comment by dahlia** [comment]
I will release 0.7.0 on this weekend.

**Comment by asottile** [comment]
fwiw @Yelp is currently using master in production and it seems to be working well

**Comment by dahlia** [comment]
Sorry for late release.  I finally released 0.7.0!  See also [changelog][1] and [PyPI][2].

[1]: http://hongminhee.org/libsass-python/changes.html#version-0-7-0
[2]: https://pypi.python.org/pypi/libsass/0.7.0
