### ISSUE TITLE
Error compiling with compass

### ISSUE THREAD

**Issue by ninapavlich** [dahlia/libsass-python#51]
I'm getting this error when trying to include compass:
"tmp/compass/compass/_support.scss:152: named arguments must precede variable-length argument"

Line 152 of _support.scss contains:
@include for-legacy-browser($browser, $range..., $threshold: $threshold, $ranges: $browsers) {

My code contains:
source = '@import "compass"; .... some styles here ....'
src_directories = ['tmp/somestyles', '/tmp/compass/']
compiled = sass.compile(string=source,include_paths=src_directories)

I'm using the latest version of Compass from Jan 15 (compass-1.0.3) and version 0.7.0 of libsass

Thanks!

**Comment by dahlia** [comment]
Could it be reproduced with the official [sassc][] as well?

[sassc]: https://github.com/sass/sassc

**Comment by lallen** [comment]
https://github.com/sass/libsass/issues/1259
Confirmed in libsass.

**Comment by asottile** [comment]
Since the bug is in the upstream libsass, I'm going to close this and let them track it there :)
