### ISSUE TITLE
libsass-python pulls different versions of libsass?

### ISSUE THREAD

**Issue by jschneier** [dahlia/libsass-python#54]
I use this excellent library as part of a build pipeline that ends with fingerprinting of my final minified css file. Yesterday (as I was preparing and then launched my site) I encountered an extremely frustrating bug.

In my requirements.txt file I have `libsass==0.7.0`. One of my servers was brought up a few weeks ago and everything worked great. In anticipation of high load I brought up a second server just before launch. The launch went off without a hitch except that sometimes the page would render with no CSS when you hit one of the servers; I traced this back to a different fingerprint on my css file. After verifying the `python-libsass` versions I ran the build process on each server individually and saw that my file outputs differed by a single line (the `@charset` declaration if you're interested). After looking at various things such as my locale I was able to fix the issue on both servers by running `pip uninstall libsass` and then `pip install libsass==0.7.0`. 

To say this was annoying to track down would be an understatement. I don't think that something like this should be even possible with the same version of the python bindings but I'm not familiar enough with C extension packaging to suggest a fix. Thanks for reading and great library!

**Comment by dahlia** [comment]
libsass-python doesn’t dynamically pull libsass, but instead the particular version of libsass is bundled into libsass-python tarball distribution.  It either does not dyload libsass shared object, but linked together statically instead.

To be honest I don’t believe that it pulls different versions of libsass.  I guess the problem is due to other cause.

**Comment by dahlia** [comment]
It would be good if it can be reproducible, but seems not possible. If by any chance you experience the same situation could you zip all files related to libsass-python in your sites-packages?

**Comment by jschneier** [comment]
I figured as much. Thanks, if it happens again I'll be sure to do a more thorough inspection.
