### ISSUE TITLE
Let's ship 0.8.0

### ISSUE THREAD

**Issue by asottile** [dahlia/libsass-python#63]
Since we've bumped libsass to 3.2 let's release!

**Comment by asottile** [comment]
lmk if you need any assistance with the rollout :D

**Comment by asottile** [comment]
err actually let's pick up the bugfixes in 3.2.1 and 3.2.2

**Comment by dahlia** [comment]
It’d better to include 3.2.1 and 3.2.2 as well.  Thank you for #64.
