### ISSUE TITLE
Document how to compile Sass syntax from a string.

### ISSUE THREAD

**Issue by dan-passaro** [dahlia/libsass-python#77]
Maybe I'm just slow today but I am having a tough time puzzling this out...

    >>> print open('file.sass').read()
    body
        font: sans-serif
        p
            font-weight: bold

    >>> import sass
    >>> print sass.compile(filename='file.sass')
    body {
      font: sans-serif; }
      body p {
        font-weight: bold; }

    >>> print sass.compile(string=open('file.sass').read())
    Traceback (most recent call last):
    ...
    CompileError: Error: invalid top-level expression
            on line 1 of stdin
    >> body
       ^

What am I doing wrong? I searched the "References" part of the docs for 'SCSS' and found nothing, I can't seem to figure out how to tell `sass.compile(string=...)` that I want Sass syntax and not SCSS.

**Comment by asottile** [comment]
This should be supported now with `indented=True` kwarg passed thanks to #102

**Comment by asottile** [comment]
You'll need at least version 0.9.3
