### ISSUE TITLE
Add import callback functionality recently incorporated into libsass

### ISSUE THREAD

**Issue by legutierr** [dahlia/libsass-python#81]
As per this issue thread...

https://github.com/sass/libsass/issues/21#issuecomment-63387229

...libsass now permits import callbacks that return source strings.  This allows systems using libsass to pull source files from the network, or database, or whatever location without having to use the filesystem.

**Comment by amcgregor** [comment]
+9001 (That's over nine thousand.)  I have a use case for database-populated CSS, and these callbacks would make my life infinitely easier than trying to mirror a DB structure under a tempfile directory.

**Comment by asottile** [comment]
#110
