### ISSUE TITLE
Source maps generation complaints

### ISSUE THREAD

**Issue by GeyseR** [dahlia/libsass-python#94]
libsass produce local path in source comments, like /Users/username/path/to/project/file.scss, that I don't actually need in my production compressed files. But, on the other hand, i want to generate source map files. Currently I can't see how to solve this

**Comment by pradyunsg** [comment]
+1

Currently, the functions to build directories do not have any way to specify the generation of `.map` files, whereas those for the filenames do.

There's nothing to handle source maps in dirname section of compile (compile_directory) or in sassutils.builder.

**Comment by asottile** [comment]
Via #130
