### ISSUE TITLE
UnicodeEncodeError: while compile font-awesome folder to folder

### ISSUE THREAD

**Issue by SquirrelMajik** [dahlia/libsass-python#95]
Font awesome host character like this:

![2015-10-19 7 09 17](https://cloud.githubusercontent.com/assets/8177626/10576315/ea3bef20-7694-11e5-8507-7daf2f760d46.png)

I think the problem only happen while you compile from a folder to another.
(single file compile is fine).

but if I try compile src folder to dest folder, the problem happened:

```python
Python 2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sass
>>> sass.compile(dirname = ('.', 'output'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/sass.py", line 510, in compile
    include_paths, precision, custom_functions,
  File "/Library/Python/2.7/site-packages/sass.py", line 170, in compile_dirname
    output_file.write(v)
UnicodeEncodeError: 'ascii' codec can't encode character u'\uf000' in position 4209: ordinal not in range(128)
>>> 
```

-----------------------
The sass file looks not problem, because when I using 'sass --update src:output' is fine too.

Thank you very much.

**Comment by asottile** [comment]
This was fixed in #72 / #82 (tested in #83) it should work correctly in the next release :)
